//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLSV_LHP_dotNetEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachMonHoc
    {
        public string TenMonHoc { get; set; }
        public string MaMonHoc { get; set; }
    }
}
